# Generated by Django 2.2.7 on 2019-12-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_suspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('duracion', models.PositiveIntegerField(help_text='Duración de la suspensión en días', verbose_name='Duración suspensión')),
                ('descripcion', models.ForeignKey(help_text='Descripción motivo suspensión', on_delete=False, to='ins.Inscripcion', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Motivo suspensión',
                'verbose_name_plural': 'Motivo suspensiones',
            },
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('descripcion', models.TextField(help_text='Descripción del motivo de la suspensión')),
                ('inscripcion', models.ForeignKey(help_text='Inscripción', on_delete=False, to='ins.Inscripcion', verbose_name='Inscripción')),
                ('motivo', models.ForeignKey(on_delete=False, to='sus.Motivo_suspension')),
            ],
            options={
                'verbose_name': 'Suspension',
                'verbose_name_plural': 'Suspensiones',
            },
        ),
    ]
