# Generated by Django 2.2.7 on 2019-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivo_suspension',
            name='descripcion',
            field=models.CharField(help_text='Descripción motivo suspensión', max_length=50, verbose_name='Descripción'),
        ),
    ]
