# Generated by Django 2.2.7 on 2019-12-03 01:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción del tipo de beneficiario, ej: Estudiante Bachillerato', max_length=45, unique=True, verbose_name='Descripcion tipo beneficiario')),
                ('uc', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de beneficiario',
                'verbose_name_plural': 'Tipos de beneficiarios',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción del género', max_length=45, unique=True, verbose_name='Descripción género')),
                ('uc', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción del documento de identidad', max_length=45, unique=True, verbose_name='Descripcion documento')),
                ('uc', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de identidad',
                'verbose_name_plural': 'Documentos de identidad',
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripcion de la dependencia a la que pertenece, ej: Sistemas, Vigilancia', max_length=45, unique=True, verbose_name='Descripcion dependencia')),
                ('uc', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('rfid', models.CharField(help_text='RFID carné o llavero    ', max_length=10, unique=True, verbose_name='RFID')),
                ('numero_documento', models.CharField(help_text='Número del documento de identidad del beneficiario', max_length=15, unique=True, verbose_name='Número de documento')),
                ('nombres', models.CharField(max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=45, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Correo electrónico')),
                ('fecha_nacimiento', models.DateField(help_text='<em>AAAA-MM-DD</em>', verbose_name='Fecha de nacimiento')),
                ('saldo', models.IntegerField(default=0, editable=False, verbose_name='Saldo')),
                ('foto', models.ImageField(upload_to='beneficiarios')),
                ('dependencia', models.ForeignKey(help_text='Dependencia a la que pertenece', on_delete=False, to='ben.Dependencia', verbose_name='Dependencia')),
                ('documento', models.ForeignKey(help_text='Documento de identidad del beneficiario', on_delete=False, to='ben.Documento', verbose_name='Documento de identidad')),
                ('genero', models.ForeignKey(help_text='Gérero del beneficiario', on_delete=False, to='ben.Genero', verbose_name='Género')),
                ('tipo_beneficiario', models.ForeignKey(help_text='Tipo de beneficiario', on_delete=False, to='ben.Tipo_beneficiario', verbose_name='Tipo beneficiario')),
                ('uc', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
            },
        ),
    ]
