# Generated by Django 2.2.7 on 2019-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ben', '0002_auto_20191202_2204'),
        ('ser', '0002_auto_20191203_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_afiliacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('descripcion', models.CharField(help_text='Descripción del tipo de afiliación', max_length=45, unique=True, verbose_name='Descripción del tipo de afiliación')),
                ('valor_porcentaje_descuento', models.IntegerField(help_text='Valor del porcentaje de descuento del tipo de afiliación', verbose_name='Porcentaje descuento')),
            ],
            options={
                'verbose_name': 'Tipo de afiliación',
                'verbose_name_plural': 'Tipos de afiliación',
                'unique_together': {('descripcion', 'valor_porcentaje_descuento')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('inasistensias_acumuladas', models.PositiveIntegerField(default=0, editable=False, help_text='Fallas acumuladas por cada servicio', verbose_name='Fallas acumuladas')),
                ('inasistensias_acumuladas_justificadas', models.PositiveIntegerField(default=0, editable=False, help_text='Fallas acumuladas con justificación por cada servicio', verbose_name='Fallas acumuladas justificadas')),
                ('inasistensias_ultimo_mes', models.PositiveIntegerField(default=0, editable=False, help_text='Fallas por cada servicio durante el último mes', verbose_name='Fallas mes')),
                ('inasistensias_justificadas_ultimo_mes', models.PositiveIntegerField(default=0, editable=False, help_text='Fallas acumuladas con justificación por cada servicio en el último mes', verbose_name='Fallas acumuladas justificadas mes')),
                ('lunes', models.BooleanField(default=True, help_text='El servicio se toma el lunes', verbose_name='Lunes')),
                ('martes', models.BooleanField(default=True, help_text='El servicio se toma el martes', verbose_name='martes')),
                ('miercoles', models.BooleanField(default=True, help_text='El servicio se toma el miércoles', verbose_name='Miercoles')),
                ('jueves', models.BooleanField(default=True, help_text='El servicio se toma el jueves', verbose_name='Jueves')),
                ('viernes', models.BooleanField(default=True, help_text='El servicio se toma el viernes', verbose_name='Viernes')),
                ('sabado', models.BooleanField(default=False, help_text='El servicio se toma el sábado', verbose_name='Sábado')),
                ('beneficiario', models.ForeignKey(help_text='Beneficiario inscripción', on_delete=False, to='ben.Beneficiario', verbose_name='Beneficiario inscripción')),
                ('servicio', models.ForeignKey(help_text='Servicio inscripción', on_delete=False, to='ser.Servicio', verbose_name='Servicio inscripción')),
                ('tipo_afiliacion', models.ForeignKey(help_text='Tipo de afiliación', on_delete=False, to='ins.Tipo_afiliacion', verbose_name='Tipo de afiliación')),
            ],
            options={
                'verbose_name': 'Inscripción servicio',
                'verbose_name_plural': 'Inscripciones Servicios',
                'unique_together': {('beneficiario', 'servicio', 'tipo_afiliacion')},
            },
        ),
    ]
