# Generated by Django 2.2.7 on 2019-12-04 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion_servicio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 21, 26, 5, 167074), help_text='Fecha en que se programa un servicio', verbose_name='Fecha programación servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='programacion_servicio',
            unique_together={('servicio', 'fecha')},
        ),
    ]
