# Generated by Django 2.2.7 on 2019-12-04 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0002_auto_20191203_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion_servicio',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2019, 12, 3, 21, 26, 32, 928095), help_text='Fecha en que se programa un servicio', verbose_name='Fecha programación servicio'),
        ),
    ]
