# Generated by Django 2.2.7 on 2019-12-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('uc', models.IntegerField(blank=True, editable=False, null=True)),
                ('um', models.IntegerField(blank=True, editable=False, null=True)),
                ('valor', models.PositiveIntegerField(help_text='Valor cancelado', verbose_name='Valor cancelado')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.CharField(default='OK', max_length=255)),
                ('inscripcion', models.ForeignKey(help_text='Inscripción', on_delete=False, to='ins.Inscripcion', verbose_name='Inscrición')),
            ],
            options={
                'verbose_name': 'Recarga',
                'verbose_name_plural': 'Recargas',
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
    ]
